### PR TITLE
added Leonardo CMS

### PR DESCRIPTION
**Pull request by michaelkuty**
Hi @rosarior what you think about Leonardo CMS ? I was before #133 and #132 ..

### CODE REVIEW

**Comment by rosarior** [comment]
I have been unable to install Leonardo to try it out, the documentation seems incomplete: http://leonardo-documentation.readthedocs.org/en/latest/en/index.html

I tried the demo site and seems incomplete too: http://store.leonardo.robotice.org/

**Comment by rosarior** [comment]
I will keep it on the pending list and try again in a few days.

**Comment by michaelkuty** [comment]
you visited only store which is under development use main demo site http://demo.cms.robotice.cz
for log in use root:admin and just try /admin or frontend editing

next we have two documentation and what you visited is just end-user with screenshot with simple actions such as add widget to page etc

please visit developers documentation which lives here http://django-leonardo.readthedocs.org/en/develop/

please check out readme on main guthub repository !

Further reading:

Demo Site (a reference build of an Leonardo project) http://demo.cms.robotice.cz
Demo Store (a reference build of an Leonardo Store project) http://store.leonardo.robotice.org/ - store is under development and will be finished soon
Developer Documentation - http://django-leonardo.readthedocs.org/en/develop/
User Documentation - http://leonardo-documentation.readthedocs.org/en/latest/en/index.html - only initial
Continuous integration homepage

please how you get it to installed state ?

here is some one liners

wget -O - https://github.com/django-leonardo/django-leonardo/raw/develop/contrib/install_leonardo.sh | sh

i created installation video which lives here https://www.youtube.com/watch?v=OU3ooXkMlrU

here is our leonardo modules 

https://github.com/leonardo-modules

thanks for any feedback !

**Comment by michaelkuty** [comment]
new stable domains
https://www.leonardo-cms.org
https://packages.leonardo-cms.org
http://demo.leonardo-cms.org
https://store.leonardo-cms.org

another sites which uses this CMS
http://www.opentcpcloud.org/
https://www.majklk.cz/

**Comment by rosarior** [comment]
Merged. A lot of improvement, good work!

**Pull request merged**
